name: limpexia_express_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0

  # Firebase (versiones estables y compatibles entre sí)
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.1
  firebase_database: ^11.1.2
  cloud_firestore: ^5.4.4

  # State Management
  provider: ^6.1.5+1

  # UI
  google_fonts: ^6.3.2
  flutter_animate: ^4.3.0

  # Utilidades
  intl: ^0.18.1
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  google_maps_flutter: ^2.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/

  # Configuración para PWA
  generate: true
